name: 'test my project'
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: 'setup node'
        with:
          node-version: '14.x'

      - name: 'install'
        run: npm i

      - name: 'test'
        run: npm run test